# Generated by Django 4.0.4 on 2022-05-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='read_post',
            field=models.ManyToManyField(to='blog.post'),
        ),
    ]
